In [2]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt 
%matplotlib inline

In [3]:
a = np.array([1, 3, 2, 4])

In [4]:
a

array([1, 3, 2, 4])

In [5]:
type(a)

numpy.ndarray

In [6]:
A = np.array([
    [3, 1, 2],
    [2, 3, 4]
])
B = np.array([
    [0, 1],
    [2, 3],
    [4, 5]
])
C = np.array([
    [0, 1],
    [2, 3],
    [4, 5],
    [0, 1],
    [2, 3],
    [4, 5]
])
print("A is a {} matrix".format(A.shape))
print("B is a {} matrix".format(B.shape))
print("C is a {} matrix".format(C.shape))

A is a (2, 3) matrix
B is a (3, 2) matrix
C is a (6, 2) matrix


In [7]:
A[0]

array([3, 1, 2])

In [8]:
A.dot(B)

array([[10, 16],
       [22, 31]])

In [9]:
B.dot(A)

array([[ 2,  3,  4],
       [12, 11, 16],
       [22, 19, 28]])

In [10]:
C.dot(A)

array([[ 2,  3,  4],
       [12, 11, 16],
       [22, 19, 28],
       [ 2,  3,  4],
       [12, 11, 16],
       [22, 19, 28]])